module.exports = [
  "Johann Sebastian Bach",
  "George Fredrick Handel",
  "Maurice Ravel",
  "Pyotr Ilyich Tchaikovsky",
  "Frederic Chopin",
  "Wolfgang Amadeus Mozart",
  "Antonio Vivaldi",
  "Pietro Locatelli",
  "Giuseppe Tartini",
  "John Dowland",
  "Josquin Desprez",
  "Claude Debussy",
  "Claudio Monteverdi",
  "Joseph Haydn",
  "Georg Philip Telemann",
  "Jean Batiste Lully",
  "Marc Antoine Carpentier",
  "Jean Philippe Rameau",
  "Johannes Brahms",
  "Richard Wagner",
  "Giuseppe Verdi",
  "Edvard Grieg",
  "Felix Mendelssohn",
  "Johann Pisendel",
  "Giovanni Battista Pergolesi",
  "Giovanni Pierluigi da Palestrina"
];